import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("node:fs", () => ({
  existsSync: vi.fn(),
  readFileSync: vi.fn(),
  writeFileSync: vi.fn(),
  renameSync: vi.fn(),
  unlinkSync: vi.fn(),
  mkdirSync: vi.fn(),
}));

vi.mock("../../../src/utils/logger.js", () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}));

// Mock paths module to avoid real filesystem calls
vi.mock("../../../src/utils/paths.js", () => ({
  getMemoryFilePath: vi.fn(
    (projectPath: string, memoryFile: string) => `${projectPath}/${memoryFile}`
  ),
  ensureDir: vi.fn(),
}));

vi.mock("../../../src/utils/tokens.js", () => ({
  formatTokens: vi.fn((n: number) => `${(n / 1000).toFixed(1)}k`),
}));

import * as fs from "node:fs";
import { MemoryWriter } from "../../../src/pipeline/memory-writer.js";
import type { DeslopifyConfig } from "../../../src/config/loader.js";
import type { Summary } from "../../../src/pipeline/summarizer.js";

const config: DeslopifyConfig = {
  threshold: 0.4,
  memoryFile: "project-memory.md",
  pollInterval: 5000,
  adapters: ["claude-code"],
  summarization: {
    provider: "same-cli",
    maxSummaryTokens: 2000,
    prompt: "Summarize",
  },
  injection: { method: "first-message", maxInjectTokens: 1500 },
  idle: { waitMs: 3000, maxWaitMs: 30000, checkInterval: 1000 },
  models: {},
};

function makeSummary(overrides?: Partial<Summary>): Summary {
  return {
    decisions: ["Use TypeScript"],
    completedTasks: ["Scaffold project"],
    openIssues: ["Flaky CI"],
    currentGoals: ["Ship v1"],
    rawSummary: "raw summary text",
    timestamp: 1700000000000,
    sessionId: "abc12345-dead-beef",
    model: "claude-sonnet-4-20250514",
    tokensAtCompaction: 80000,
    ...overrides,
  };
}

describe("MemoryWriter", () => {
  let writer: MemoryWriter;

  beforeEach(() => {
    writer = new MemoryWriter(config);
  });

  describe("write", () => {
    it("creates new memory file with header when none exists", async () => {
      vi.mocked(fs.existsSync).mockReturnValue(false);

      const result = await writer.write(makeSummary(), "/project");

      expect(result).toBe("/project/project-memory.md");

      // Should write to .tmp first
      const writeCall = vi.mocked(fs.writeFileSync).mock.calls[0];
      expect(writeCall[0]).toBe("/project/project-memory.md.tmp");
      const content = writeCall[1] as string;
      expect(content).toContain("# Project Memory");
      expect(content).toContain("Auto-generated by");
      expect(content).toContain("## Session Checkpoint");
      expect(content).toContain("Use TypeScript");
      expect(content).toContain("Scaffold project");
      expect(content).toContain("Flaky CI");
      expect(content).toContain("Ship v1");

      // Should rename to final path
      expect(fs.renameSync).toHaveBeenCalledWith(
        "/project/project-memory.md.tmp",
        "/project/project-memory.md"
      );
    });

    it("appends to existing memory file", async () => {
      vi.mocked(fs.existsSync).mockReturnValue(true);
      vi.mocked(fs.readFileSync).mockReturnValue(
        "# Project Memory\n\n## Session Checkpoint - old"
      );

      await writer.write(makeSummary(), "/project");

      const writeCall = vi.mocked(fs.writeFileSync).mock.calls[0];
      const content = writeCall[1] as string;
      // Should NOT have a second header
      expect(content).toContain("# Project Memory");
      expect(content).toContain("Session Checkpoint - old");
      // Should have the new entry appended
      expect(content).toContain("## Session Checkpoint -");
      expect(content).toContain("Use TypeScript");
    });

    it("includes model and token info in entry", async () => {
      vi.mocked(fs.existsSync).mockReturnValue(false);

      await writer.write(makeSummary(), "/project");

      const content = vi.mocked(fs.writeFileSync).mock.calls[0][1] as string;
      expect(content).toContain("claude-sonnet-4-20250514");
      expect(content).toContain("80.0k");
      expect(content).toContain("abc12345...");
    });

    it("omits empty sections", async () => {
      vi.mocked(fs.existsSync).mockReturnValue(false);

      await writer.write(
        makeSummary({ decisions: [], openIssues: [] }),
        "/project"
      );

      const content = vi.mocked(fs.writeFileSync).mock.calls[0][1] as string;
      expect(content).not.toContain("### Architectural Decisions");
      expect(content).not.toContain("### Open Issues");
      // Non-empty sections should be present
      expect(content).toContain("### Completed Tasks");
      expect(content).toContain("### Current Goals");
    });

    it("cleans up temp file on write failure", async () => {
      vi.mocked(fs.existsSync).mockImplementation((p) => {
        if (String(p).endsWith(".tmp")) return true;
        return false;
      });
      vi.mocked(fs.writeFileSync).mockImplementation(() => {
        throw new Error("disk full");
      });

      await expect(writer.write(makeSummary(), "/project")).rejects.toThrow(
        "disk full"
      );

      expect(fs.unlinkSync).toHaveBeenCalledWith(
        "/project/project-memory.md.tmp"
      );
    });

    it("survives temp cleanup failure silently", async () => {
      vi.mocked(fs.existsSync).mockImplementation((p) => {
        if (String(p).endsWith(".tmp")) return true;
        return false;
      });
      vi.mocked(fs.writeFileSync).mockImplementation(() => {
        throw new Error("disk full");
      });
      vi.mocked(fs.unlinkSync).mockImplementation(() => {
        throw new Error("unlink failed");
      });

      // Should not double-throw
      await expect(writer.write(makeSummary(), "/project")).rejects.toThrow(
        "disk full"
      );
    });
  });

  describe("getLatestEntry", () => {
    it("returns null when memory file does not exist", () => {
      vi.mocked(fs.existsSync).mockReturnValue(false);

      expect(writer.getLatestEntry("/project")).toBeNull();
    });

    it("returns null when file has no checkpoint entries", () => {
      vi.mocked(fs.existsSync).mockReturnValue(true);
      vi.mocked(fs.readFileSync).mockReturnValue("# Project Memory\n\nJust a header.");

      expect(writer.getLatestEntry("/project")).toBeNull();
    });

    it("returns the last checkpoint entry", () => {
      vi.mocked(fs.existsSync).mockReturnValue(true);
      vi.mocked(fs.readFileSync).mockReturnValue(
        "# Header\n\n## Session Checkpoint - 2024-01-01\nFirst entry\n\n## Session Checkpoint - 2024-02-01\nSecond entry"
      );

      const result = writer.getLatestEntry("/project");
      expect(result).toContain("## Session Checkpoint - 2024-02-01");
      expect(result).toContain("Second entry");
      expect(result).not.toContain("First entry");
    });
  });

  describe("getFullMemory", () => {
    it("returns null when file does not exist", () => {
      vi.mocked(fs.existsSync).mockReturnValue(false);

      expect(writer.getFullMemory("/project")).toBeNull();
    });

    it("returns full file content", () => {
      vi.mocked(fs.existsSync).mockReturnValue(true);
      vi.mocked(fs.readFileSync).mockReturnValue("full memory content");

      expect(writer.getFullMemory("/project")).toBe("full memory content");
    });
  });
});
