import * as fs from "node:fs";
import * as path from "node:path";
import type { DeslopifyConfig } from "../config/loader.js";
import type { Summary } from "./summarizer.js";
import { getMemoryFilePath, ensureDir } from "../utils/paths.js";
import { formatTokens } from "../utils/tokens.js";
import { logger } from "../utils/logger.js";

export class MemoryWriter {
  private config: DeslopifyConfig;

  constructor(config: DeslopifyConfig) {
    this.config = config;
  }

  /**
   * Write the summary to the project's memory file.
   * Uses write-ahead pattern: writes to temp file first, then moves.
   */
  async write(summary: Summary, projectPath: string): Promise<string> {
    const memoryPath = getMemoryFilePath(projectPath, this.config.memoryFile);
    const tempPath = memoryPath + ".tmp";

    logger.info(`Writing memory to ${memoryPath}`);

    // Build the new entry
    const entry = this.formatEntry(summary);

    // Write-ahead: create temp file first
    try {
      let existingContent = "";
      if (fs.existsSync(memoryPath)) {
        existingContent = fs.readFileSync(memoryPath, "utf-8");
      }

      const newContent = existingContent
        ? existingContent + "\n\n" + entry
        : this.buildHeader() + "\n\n" + entry;

      // Write to temp file first (write-ahead for safety)
      ensureDir(path.dirname(memoryPath));
      fs.writeFileSync(tempPath, newContent, "utf-8");

      // Atomic rename
      fs.renameSync(tempPath, memoryPath);

      logger.info(`Memory written successfully: ${memoryPath}`);
      return memoryPath;
    } catch (err) {
      // Clean up temp file on failure
      try {
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
      } catch {}

      logger.error("Failed to write memory file", { error: String(err) });
      throw err;
    }
  }

  private buildHeader(): string {
    return `# Project Memory

> Auto-generated by [deslopify](https://github.com/deslopify/deslopify) - Context management for AI CLIs.
> This file contains summarized session history to preserve context across compactions.

---`;
  }

  private formatEntry(summary: Summary): string {
    const date = new Date(summary.timestamp).toISOString();
    const tokens = formatTokens(summary.tokensAtCompaction);

    let entry = `## Session Checkpoint - ${date}\n\n`;
    entry += `> Model: \`${summary.model}\` | Tokens at compaction: ${tokens} | Session: \`${summary.sessionId.slice(0, 8)}...\`\n\n`;

    if (summary.decisions.length > 0) {
      entry += `### Architectural Decisions\n`;
      entry += summary.decisions.map((d) => `- ${d}`).join("\n");
      entry += "\n\n";
    }

    if (summary.completedTasks.length > 0) {
      entry += `### Completed Tasks\n`;
      entry += summary.completedTasks.map((t) => `- ${t}`).join("\n");
      entry += "\n\n";
    }

    if (summary.openIssues.length > 0) {
      entry += `### Open Issues\n`;
      entry += summary.openIssues.map((i) => `- ${i}`).join("\n");
      entry += "\n\n";
    }

    if (summary.currentGoals.length > 0) {
      entry += `### Current Goals\n`;
      entry += summary.currentGoals.map((g) => `- ${g}`).join("\n");
      entry += "\n\n";
    }

    entry += `---`;
    return entry;
  }

  /**
   * Read the latest memory entry for context injection
   */
  getLatestEntry(projectPath: string): string | null {
    const memoryPath = getMemoryFilePath(projectPath, this.config.memoryFile);
    if (!fs.existsSync(memoryPath)) return null;

    const content = fs.readFileSync(memoryPath, "utf-8");

    // Extract the last session checkpoint
    const entries = content.split(/## Session Checkpoint/);
    if (entries.length < 2) return null;

    const latest = entries[entries.length - 1];
    return `## Session Checkpoint${latest}`.trim();
  }

  /**
   * Get the full memory content
   */
  getFullMemory(projectPath: string): string | null {
    const memoryPath = getMemoryFilePath(projectPath, this.config.memoryFile);
    if (!fs.existsSync(memoryPath)) return null;
    return fs.readFileSync(memoryPath, "utf-8");
  }
}
